# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks: [
        {
          "always_run": false,
          "entry": "/usr/bin/env fourmolu --mode inplace ",
          "exclude": "^$",
          "fail_fast": false,
          "files": "\\.l?hs(-boot)?$",
          "id": "fourmolu",
          "language": "system",
          "name": "fourmolu",
          "pass_filenames": true,
          "require_serial": false,
          "stages": [
            "pre-commit"
          ],
          "types": [
            "file"
          ],
          "types_or": [],
          "verbose": false
        }
    ]