name:                lang
version:             0.1.0.0
github:              "Litoprobka/lang"
license:             BSD2
author:              "Peter Burtsev"
copyright:           "2024 Peter Burtsev"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Litoprobka/lang#readme>

language: GHC2021

default-extensions:
  - NoImplicitPrelude
  - BlockArguments
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- relude >= 1.2.1.0 && < 2
- megaparsec >= 9.5.0 && < 10
- parser-combinators >= 1.3 && < 2
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lang

tests:
  lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    defaults: hspec/hspec@master
    dependencies:
    - lang
